### ISSUE TITLE
Get rid of `Reflections` in `PluginCompatTesterHooks`

### ISSUE THREAD

**Issue by jglick** [jenkinsci/plugin-compat-tester#394]
context: https://github.com/jenkinsci/plugin-compat-tester/pull/392#discussion_r1067235883

Introduced in #16, this is an overly complicated and fragile way to find implementations of something in the classpath. Use `ServiceLoader` etc.

**Comment by basil** [comment]
Hello Jesse, I see you have taken an interest in the project I am working on, as evidenced by the numerous issues you are filing. Should you be involved as a full member of this project, including being assigned issues?

**Comment by jglick** [comment]
Currently I cannot commit to devoting time to work in this area.

**Comment by basil** [comment]
Then I would ask that you please file issues from the perspective of an end user and kindly refrain from acting as a de facto unsolicited project lead or technical program manager of a project that you are not working on (which is what these cleanup issues and code reviews are starting to feel like). Sorry, but working on technical debt like this is demoralizing enough as it is without the added burden of interacting with people who have opinions but cannot commit to helping. If you would give me the space, I am perfectly capable of discovering issues like this and filing them on my own. James is also perfectly capable of reviewing my PRs. Furthermore, there is more intrinsic motivation to work on such cleanup when it is part of an organic self-guided process rather than requests coming from outside. Phrased differently, cleanup requests from people who cannot commit to helping destroy my intrinsic motivation to do cleanup work, which is the fuel for this project.

Would love to collaborate with you on this, but true collaboration is not just filing issues and reviewing the results from a distance. True collaboration is being part of making the solution a reality. Door is always open if you want to do that.
